import { Patent } from '../types';

export const generateLegalTechReport = (patent: Patent, analysis: string, priorArtReport?: string) => {
  const date = new Date().toLocaleDateString('en-GB', {
    day: 'numeric', month: 'long', year: 'numeric', hour: '2-digit', minute: '2-digit'
  });
  
  const refId = Math.random().toString(36).substring(2, 10).toUpperCase();

  const reportContent = `
PATENTOS INTELLIGENCE REPORT
=============================================================================
REFERENCE ID : ${refId}
DATE         : ${date}
GENERATED BY : PatentOS Autonomous Agent (v2.4-PROD)
=============================================================================

[ DISCLAIMER ]
This document contains technical analysis generated by an Artificial Intelligence 
system. It DOES NOT constitute legal advice, freedom-to-operate clearance, or 
patent invalidity opinions. Consult a qualified patent attorney for binding 
legal counsel.
=============================================================================

1. ASSET IDENTIFICATION
-----------------------
Patent ID       : ${patent.id}
Title           : ${patent.title}
Assignee        : ${patent.assignee}
Status          : ${patent.status}
Filing Date     : ${patent.filingDate}
Expiration      : ${patent.expirationDate}
Jurisdictions   : ${patent.jurisdictions.join(', ')}

2. STRATEGIC METRICS
--------------------
UK Replicability Score : ${patent.ukReplicabilityScore}/100
Risk Score             : ${patent.riskScore}/100
Opportunity Type       : ${patent.opportunityType}
Rev. Eng. Feasibility  : ${patent.reverseEngineeringFeasibility}
Trade Secret Candidate : ${patent.isTradeSecretCandidate ? 'YES' : 'NO'}

3. EXECUTIVE VERDICT
--------------------
${patent.ukReplicabilityReason}

=============================================================================
4. DEEP DIVE ANALYSIS (FREEDOM TO OPERATE)
=============================================================================

${analysis}

=============================================================================
5. PRIOR ART & INVALIDITY RISK (SIMULATED)
=============================================================================

${priorArtReport ? priorArtReport : "No prior art analysis requested for this session."}

───────────────────────────────────────────────
⚠ NOTICE
This report contains automated, AI-generated assessments and simulated prior art results. 
It DOES NOT constitute legal advice. No liability accepted. 
Consult a qualified IP attorney before acting on this content.
Report ID: ${refId}
Generated: ${date}
Version: PatentOS v1.0-ALPHA
───────────────────────────────────────────────
`;

  const element = document.createElement("a");
  const file = new Blob([reportContent], {type: 'text/plain'});
  element.href = URL.createObjectURL(file);
  element.download = `PatentOS_${patent.id}_${refId}_Report.txt`;
  document.body.appendChild(element);
  element.click();
  document.body.removeChild(element);
};